MEB-135: Standardizing MetaBrainz Logos
metabrainz/picard-website pull request #248
Opened 2022-04-01 23:57 UTC by Aerozol

Updating logos to current version: Taller caps, Roboto Black font

2022-04-02 10:57 UTC, phw requested changes
Thanks a lot.

Only thing I'd change is have the new logo again define a proper view size. The old logo defines a size with a height of 30px (https://picard.musicbrainz.org/static/img/picard-navbar-icon.svg). That the same as e.g. on ListenBrainz.

I had this short WTF moment when I tested this locally and the CSS failed to load, resulting in a gigantic logo dominating the screen :D

2022-04-02 11:19 UTC, phw commented
@Aerozol Might PICARD-2446 be something you would tackle? This itches me for a while.

2022-04-02 23:18 UTC, Aerozol commented
Thanks for testing @phw!
Turns out it's an easy fix - uncheck 'responsive' in the save dialogue in Illustrator. Phew haha. Let me know if this file tests okay and then I'll make the changes on the other pull requests.

2022-04-12 05:39 UTC, phw approved these changes

2022-04-12 06:25 UTC, merged